

/**
 * Generic client interface for Monitor callbacks.
 * A client can register a Consumer callback anytime with the system
 * Monitor.
 * The client specifies what type of event it is interested in e.g.
 * periodic, on change, trigger etc. and specifies a Consumer object.
 * Everytime the Monitor wants to signal an event to the client it
 * triggers the Consumer callback (handler).
 * Consumer is created locally by the client.
 **/
interface Consumer
{
/**
 * pending (readonly) - number of monitors using this Consumer
 **/
	readonly attribute long pending;
/**
 * callback to be trigerred by Montiro everytime there is an event
@param info info passed by Monitor to client
 **/
	oneway void handler(in MonitorInfo info);
};



