/**
 * Local interface for grouped Device requests (locality constrained).
 * GroupDevice is a client nterface for defining groups of control objects.
 * Once a group of device has been defined it is possible to with a single 
 * call execute a command on them.
 * The GroupDevice will optimize the request so that it is executed
 * in the shortest possible time and respects the order requested.
 * GroupDevice exists only locally in the client i.e.
 * it is not a network addressable object.
 **/
 
interface GroupDevice
{
/**
 * device_list (readonly) - list of devices presently member of this group
 **/
	readonly attribute DeviceList device_list;
/**
 * add a list of devices to the group
@param devices list of device to add
@return nothing.
*/
	void add (in DeviceList devices) raises(DevFailed);
/**
 * remove a list of devices from the group
@param devices list of device to remove
@return nothing.
*/
	void remove (in DeviceList devices) raises(DevFailed);

/**
 * execute a command on a group of devices synchronously with
 * no input parameter and one output parameter
@param command ascii string e.g. "On"
@param argin command input parameter e.g. float
@return command result.
 **/
	any command_inout(in string command, in any argin) raises(DevFailed);


/**
 * execute a command on a group of devices asynchronously with
 * one input parameter and one output parameter, callback is triggered on 
 * completion
@param command ascii string e.g. "On"
@param argin command parameter
@param user_data passed to callback e.g. short
@param callback to be called on completion
@return nothing.
 **/
	oneway void command_inout_async(in string command, in any argin, in any user_data, in CallBack cb);
};


