
	
/**
 * Generic client interface for asynchronous Device callbacks.
 * Every Device client which wants to dispatch commands 
 * asynchronously has to create one or more CallBack objects.
 * The CallBack object is passed as input parameter to the
 * asynchronous call.
 * It is invoked by the device server when the asynchronous
 * call has completed.
 * All return arguments are passed via the DevCallBackData struct.
 * The CallBack object has a pending attribute to indicate the number of
 * requests waiting for completion.
 */
 
interface CallBack
{
/**
 * pending (readonly) - number of request pending
 **/
	readonly attribute long pending;
/**
 * method to invoke when calling client back
@param info callback information
@return nothing
 **/
	void handler(in DevCallBackInfo info);
/**
 * method to invoke when calling a client back after a grouped call
@param info_list list of callback information
@return nothing
 **/
	void handler_list(in DevCallBackInfoList info);
};
