

/**
 * A System wide interface to automating Tcl scripts.
 * TclAutomate allows a client to set up a Tcl script which
 * talks to TANGO control objects and run it. 
 * The client can interrogate the script while it is running
 * retrieve results, stop it or save it.
 * The idea behind TclAutomate is to give the client
 * a way to do sequencing and batching via the powerful Tcl language.
 **/
 
 
interface TclAutomate
{
/**
 * start script running
@param args arguments to be passed to script
@param cb client callback to call on completion
@return nothing
 **/
	void run(in DevVarStringArray args, in CallBack cb) raises(DevFailed);
/**
 * load script 
@param name of new script
@param script new script to load
@return nothing
 **/
	void load(in string name,in string script) raises(DevFailed);
/**
 * clear script
@param name of script to clear
@return nothing
 **/
	void clear(in string name) raises(DevFailed);
/**
 * stop executing script
@param name of script to stop
@return nothing
 **/
	void stop(in string name) raises(DevFailed);
/**
 * continue executing script
@param name of script to continue executing
@return nothing
 **/
	void continue(in string name) raises(DevFailed);
/**
 * restart script
@param name of script to restart
@return nothing
 **/
	void restart(in string name) raises(DevFailed);
/**
 * open file as script
@param file name of file to open
@return nothing
 **/
	void open(in string file) raises(DevFailed);
};
